SELECT
date,
client,
channel,
platform,
goal_number,
ifnull(sum(users),0) users,
ifnull(sum(sessions),0) sessions,
ifnull(sum(warm_goal_completions),0) warm_goal_completions, 
ifnull(sum(hot_goal_completions),0) hot_goal_completions, 
ifnull(sum(cost),0) cost,
ifnull(sum(impressions),0) impressions,
ifnull(sum(clicks),0) clicks,
ifnull(sum(conversions),0) conversions,
ifnull(sum(new_pages),0) new_pages,
ifnull(sum(retired_pages),0) retired_pages,
ifnull(sum(leads),0) leads,
ifnull(sum(opportunities),0) opportunities,
ifnull(sum(deals),0) deals,
ifnull(sum(revenue),0) revenue,
ifnull(sum(xero_revenue),0) xero_revenue,
ifnull(sum(assisted_conversions),0) assisted_conversions,
ifnull(sum(ref_domains),0) ref_domains,
ifnull(sum(link_count),0) link_count,
ifnull(sum(domain_authority),0) domain_authority,
ifnull(sum(organic_keywords),0) organic_keywords,
ifnull(sum(organic_traffic),0) organic_traffic,
ifnull(sum(organic_value),0) organic_value,  
ifnull(sum(top_5_keywords),0) top_5_keywords,
ifnull(sum(realized_impressions),0) realized_impressions,
ifnull(sum(available_impressions),0) available_impressions,
ifnull(sum(impression_share),0) impression_share
FROM   
{{ref('agg_all_daily_union')}} 
GROUP BY 
date,
client,
channel,
platform,
goal_number