SELECT
date,
client,
channel,
platform,
goal_number,
sum(users) users,
sum(sessions) sessions,
sum(warm_goal_completions) warm_goal_completions, 
sum(hot_goal_completions) hot_goal_completions, 
sum(cost) cost,
sum(impressions) impressions,
sum(clicks) clicks,
sum(conversions) conversions,
sum(new_pages) new_pages,
sum(retired_pages) retired_pages,
sum(leads) leads,
sum(opportunities) opportunities,
sum(deals) deals,
sum(revenue) revenue,
sum(xero_revenue) xero_revenue,
sum(assisted_conversions) assisted_conversions,
sum(ref_domains) ref_domains,
sum(link_count) link_count,
sum(domain_authority) domain_authority,
sum(organic_keywords) organic_keywords,
sum(organic_traffic) organic_traffic,
sum(organic_value) organic_value,  
sum(top_5_keywords) top_5_keywords,
sum(realized_impressions) realized_impressions,
sum(available_impressions) available_impressions,
sum(impression_share) impression_share
FROM   
{{ref('agg_all_daily_union')}} 
GROUP BY 
date,
client,
channel,
platform,
goal_number